In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
d1=pd.read_csv("C:/Users/aman/Desktop/BITS Research/Data analysis/copy- LoRaWAN dataset.csv")
d1.head()


index        timestamp device_id  distance    ht  hr  ptx  ltx     gtx  \
0      1  4/11/2021 16:24       EN1      2140  40.0   5   20  1.0  2.9955   
1      2  4/11/2021 16:25       EN1      2140  40.0   5   20  1.0  2.9955   
2      3  4/11/2021 16:26       EN1      2140  40.0   5   20  1.0  2.9955   
3      4  4/11/2021 16:27       EN1      2140  40.0   5   20  1.0  2.9955   
4      5  4/11/2021 16:28       EN1      2140  40.0   5   20  1.0  2.9955   

    lrx  ...    rh     bp  pm2_5  rssi  snr       toa  experimental_pl  \
0  4.25  ...  56.2  852.3    6.0   -72  7.8  0.205824         93.90644   
1  4.25  ...  55.5  852.3   18.0   -77  6.5  0.246784         98.90644   
2  4.25  ...  54.9  852.3   23.0   -73  6.2  0.287744         94.90644   
3  4.25  ...  54.8  852.4   51.0   -77  6.0  0.328704         98.90644   
4  4.25  ...  55.1  852.3   42.0   -73  7.0  0.288768         94.90644   

   energy        esp         pn  
0  0.0880 -72.666832 -80.466832  
1  0.0961 -77.877360 -84.377360  
2  0.1273 -73.933808 -80.133808  
3  0.1302 -77.973228 -83.973228  
4  0.1263 -73.790097 -80.790097  

[5 rows x 25 columns]

In [9]:
d1.shape


(930753, 25)

In [11]:
d1.isnull().sum()

index              0
timestamp          0
device_id          0
distance           0
ht                 0
hr                 0
ptx                0
ltx                0
gtx                0
lrx                0
grx                0
frequency          0
sf                 0
frame_length       0
temperature        0
rh                 0
bp                 0
pm2_5              0
rssi               0
snr                0
toa                0
experimental_pl    0
energy             0
esp                0
pn                 0
dtype: int64

In [13]:
d1['distance'].unique()

array([2140, 3450, 6100, 8260], dtype=int64)

In [17]:
#Height of Atenna of End Devices
d1['ht'].unique()


array([40. , 12.5,  8. , 12. ])

In [15]:
#Height of Antenna of Gateway
d1['hr'].unique()

array([5], dtype=int64)

In [16]:
#Transmitter (EN) radiated power in dBm
d1['ptx'].unique()

array([20], dtype=int64)

In [18]:
#Transmitter (EN) losses associated with cables and connectors, in dB
d1['ltx'].unique()

array([ 1.  , 11.75])

In [19]:
#Transmitter (EN) antenna gain
d1['gtx'].unique()

array([2.9955, 2.9028, 2.9229, 8.536 ])

In [20]:
# Receiver (GW) losses associated with cables and connectors
d1['lrx'].unique()

array([4.25])

In [21]:
#Receiver (GW) antenna gain 
d1['grx'].unique()

array([4.16094])

In [22]:

d1['frequency'].unique()

array([904900000, 903900000, 904700000, 904100000, 904500000, 905100000,
       905300000, 904300000], dtype=int64)

In [23]:
d1['frame_length'].unique()

array([ 26,  35,  44,  53,  10,  55, 102, 148, 195, 241,   9,  32,  78,
       101, 124,  18,  11], dtype=int64)

In [24]:
d1['temperature'].unique()


array([26.5, 26.4, 26.3, 26.1, 26. , 25.9, 25.8, 25.7, 25.6, 25.5, 25.4,
       25.3, 25.2, 25.1, 25. , 26.2, 26.6, 26.7, 26.8, 26.9, 27. , 27.1,
       27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8, 27.9, 28. , 28.1, 28.2,
       28.3, 28.5, 28.6, 28.7, 28.8, 28.9, 28.4, 29. , 29.1, 29.2, 29.3,
       29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. , 30.1, 30.2, 30.3, 30.4,
       30.5, 30.7, 30.9, 31.1, 31.2, 31.4, 31.5, 31.6, 31.3, 30.8, 24.7,
       24.1, 23.6, 23.8, 23.3, 23.2, 23.1, 23. , 22.9, 22.6, 22.5, 22.4,
       22.2, 22.1, 22. , 21.9, 21.8, 21.7, 22.3, 22.7, 23.7, 23.5, 24. ,
       24.2, 24.3, 24.4, 23.9, 24.5, 24.8, 24.9, 23.4, 22.8, 17.2, 17.3,
       17.4, 17.5, 17.6, 17.1, 17. , 16.9, 17.7, 17.8, 17.9, 18. , 18.1,
       18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. , 19.1, 19.2,
       19.4, 19.3, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1, 20.2, 20.8,
       20.9, 21. , 21.1, 21.2, 21.3, 21.4, 20.7, 20.6, 20.5, 20.4, 20.3,
       21.5, 21.6, 24.6, 30.6, 31. , 31.7, 31.8, 31

In [28]:
 #Relative humidity of the environment, in %
d1['rh'].unique()


array([56.2, 55.5, 54.9, 54.8, 55.1, 55.7, 55.9, 57.2, 56.1, 54.4, 54.1,
       55.4, 54.3, 56. , 55.3, 56.3, 56.5, 55.6, 53.5, 53.2, 57.7, 56.6,
       57.3, 57.1, 57.5, 56.7, 58.3, 57. , 58.4, 58.6, 56.8, 57.4, 56.9,
       54.7, 57.8, 54. , 57.6, 56.4, 58.1, 57.9, 55.8, 54.2, 54.5, 53.9,
       53.4, 52.5, 53.1, 53. , 52.6, 52. , 51.7, 50.3, 50.5, 51.5, 50.9,
       51.2, 51.3, 50.1, 49.9, 48.8, 49.6, 49.3, 50.2, 50.7, 52.7, 51.8,
       50.8, 52.2, 52.1, 52.8, 52.4, 51.6, 52.9, 50.6, 53.3, 51.4, 51.1,
       49.8, 48.5, 51. , 51.9, 50.4, 49.2, 49.7, 49.4, 48.9, 49. , 48.7,
       48.4, 48.6, 47.7, 50. , 48.3, 48.1, 47.9, 49.5, 47.4, 47.3, 47.2,
       47.5, 46.6, 46. , 46.1, 46.7, 47.8, 48.2, 49.1, 48. , 46.5, 45.9,
       47. , 46.9, 46.8, 47.6, 45.3, 46.2, 47.1, 46.3, 45.8, 45.1, 45.5,
       45.7, 45.6, 44.3, 45. , 44. , 44.6, 46.4, 45.4, 43.9, 44.8, 44.1,
       44.7, 44.4, 43.5, 43.4, 42.8, 43. , 42.9, 42.4, 42. , 43.8, 42.1,
       42.5, 41.7, 41.6, 42.3, 43.3, 44.9, 42.2, 42

In [30]:
# Barometric pressure of the environment, in hPa

d1['bp'].unique()

array([852.3, 852.4, 852.2, 852.1, 852. , 851.9, 851.8, 851.7, 851.6,
       851.5, 851.4, 851.3, 851.2, 851.1, 851. , 850.9, 850.8, 850.7,
       850.6, 850.5, 850.4, 850.3, 850.2, 850.1, 850. , 849.9, 849.8,
       849.7, 849.6, 849.5, 849.4, 849.3, 849.2, 849.1, 849. , 848.9,
       848.8, 848.7, 848.6, 848.5, 848.4, 848.2, 848.3, 848.1, 848. ,
       847.9, 847.7, 847.8, 847.6, 847.4, 847.5, 847. , 847.3, 847.2,
       846.7, 847.1, 852.5, 852.6, 852.7, 852.8, 852.9, 853. , 853.1,
       853.2, 846.9, 846.8, 846.6, 846.5, 846.4, 846.3, 846.1, 846.2,
       846. , 845.9, 845.8, 845.7, 845.6, 845.5, 845.3, 845.4, 845.1,
       845.2, 845. , 844.9, 844.8, 844.7, 844.5, 844.6, 844.4, 844.3,
       844.2, 844. , 853.8, 853.6, 853.5, 853.4, 853.3, 853.9, 854. ,
       853.7, 854.1, 854.2, 854.3, 854.4, 854.5, 854.6, 854.7, 854.8,
       827.5, 827.6, 827.4, 827.3, 827.2, 827.1, 827. , 826.9, 828.3,
       828.4, 828.2, 828.1, 828. , 827.9, 827.8, 827.7, 826.8, 826.7,
       826.6, 826.5,

In [32]:
#Particulate matter PM2.5 of the environment, in µg/m3
d1['pm2_5'].unique()

array([ 6. , 18. , 23. , 51. , 42. , 55. ,  5. ,  0. ,  8. , 34. , 14. ,
        4. ,  2. , 10. ,  3. ,  9. ,  1. , 21. , 26. , 25. , 29. ,  7. ,
       13. , 33. , 27. , 15. , 19. , 17. , 43. , 11. , 16. , 35. , 12. ,
       50. , 24. , 81. , 31. , 22. , 48. , 28. , 20. , 49. , 41. , 36. ,
       75. , 51.2, 30. , 38. , 45. , 32. , 70. , 59. , 56. , 37. , 40. ,
       46. , 47. , 71. , 60. , 39. , 61. , 62. , 64. , 67. , 44. , 52. ,
       58. , 53. , 57. , 63. , 54. , 66. , 79. , 80. , 68. , 84. , 65. ,
       73. , 76. , 69. , 88. , 78. , 77. , 72. , 74. , 85. , 82. , 83. ,
       86. , 89. , 87. , 91. , 93. , 92. , 90. , 14.8, 31.8, 14.4, 79.4,
       35.4, 19.4, 48.8,  2.4, 18.4, 29.4, 66.4, 36.8, 49.4,  8.8, 37.4,
        6.4,  4.4])

In [33]:
d1['rssi'].unique()

array([ -72,  -77,  -73,  -74,  -71,  -75,  -70,  -69,  -76,  -68,  -67,
        -66,  -65,  -64,  -78,  -63,  -79,  -80,  -81,  -82,  -84,  -83,
        -85,  -86,  -92,  -96,  -93,  -98,  -94,  -90,  -91,  -95,  -97,
        -99, -100, -101,  -89,  -88,  -87, -102], dtype=int64)

In [34]:
d1['snr'].unique()

array([  7.8,   6.5,   6.2,   6. ,   7. ,   6.8,   5.8,   4.5,   5.2,
         5.5,   7.2,   4.8,   5. ,   3.2,   1.8,   7.5,   4.2,   4. ,
         2. ,   3.8,   3. ,   2.5,   3.5,   1.2,  -2. ,   1.5,   2.2,
         2.8,  -1.8,   0.5,   0.8,   8. ,   8.8,   8.5,   8.2,   9. ,
         9.8,   9.2,   9.5,  10. ,  10.2,  10.5,  -1. ,  -0.8,  -0.2,
         0.2,  -1.5,   1. ,  -1.2,  10.8,  -0.5,  -2.8,  -2.5,  -3.2,
        -3.8,  -3.5,  12.8,  -2.2,  -3. ,  -4. ,  -4.5,  -4.2,  -5. ,
        -5.5,  -5.8,  -4.8,  -5.2,  -6.2,  -6.5, -13. , -12.5, -12. ,
       -12.8, -14.5, -11.2, -10. , -13.8, -11.5, -12.2, -13.2, -14.2,
       -11. , -15.2, -11.8, -13.5, -10.8, -15. , -15.8, -14.8, -14. ,
       -10.5, -15.5, -10.2, -16. , -16.2, -16.5, -17. , -16.8, -17.2,
        -9.8, -17.5,  -9.2,  -8.5,  -9.5,  -9. ,  -8. ,  -8.8,  -8.2,
        -7.8,  -7.5,  -7.2, -18.5,  -7. ,  -6.8,  -6. , -17.8, -18. ])

In [35]:
d1['toa'].unique()

array([0.205824, 0.246784, 0.287744, 0.328704, 0.288768, 0.107776,
       0.174336, 0.240896, 0.312576, 0.379136, 0.072192, 0.133632,
       0.195072, 0.246272, 0.307712, 0.369152, 0.144384, 0.185344,
       0.247808, 0.041216, 0.082432])

In [36]:
# Experimental path loss (in dB) calculated by ptx + gtx + grx − lrx − rssi

d1['experimental_pl'].unique()

array([ 93.90644,  98.90644,  94.90644,  95.90644,  92.90644,  96.90644,
        91.90644,  90.90644,  97.90644,  89.90644,  88.90644,  87.90644,
        86.90644,  85.90644,  99.90644,  84.90644,  96.81374,  95.81374,
        98.81374,  94.81374,  93.81374, 100.8137 ,  99.81374,  97.81374,
       101.8137 , 102.8137 ,  92.81374, 103.8137 , 105.8137 , 104.8137 ,
       106.8137 , 107.8137 ,  91.81374,  90.81374, 103.0838 , 107.0838 ,
       104.0838 , 109.0838 , 105.0838 , 101.0838 , 102.0838 , 106.0838 ,
       108.0838 , 110.0838 , 111.0838 , 112.0838 , 100.0838 ,  99.08384,
        98.08384, 113.0838 ,  97.08384, 111.4469 , 114.4469 , 112.4469 ,
       113.4469 , 109.4469 , 110.4469 , 108.4469 , 115.4469 , 105.4469 ,
       107.4469 , 106.4469 , 117.4469 , 104.4469 , 116.4469 , 103.4469 ,
       102.4469 , 101.4469 ])

In [38]:
#Consumed energy of the current transmission, in Joules
d1['energy'].unique()

array([0.088 , 0.0961, 0.1273, ..., 0.0918, 0.0123, 0.0272])

In [39]:
#Effective signal power of the current transmission, in dBm
d1['esp'].unique()

array([-72.66683164, -77.87736039, -73.93380808, ..., -86.81412566,
       -81.8187948 , -92.81209676])

In [41]:
#Noise power, in dBm
d1['pn'].unique()

array([-80.46683164, -84.37736039, -80.13380808, ..., -81.01412566,
       -77.3187948 , -84.61209676])

In [5]:
d1.distance.value_counts()

6100    344688
2140    201595
8260    201428
3450    183042
Name: distance, dtype: int64